services:
  redis:
    image: redis:latest
    container_name: redis
    restart: no
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: no
    ports:
      - 8001:8001 #open in browser 127.0.0.1:8001 for gui
    volumes:
      - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data: